/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Control.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author Brn Hurtado
 * 
 */
public class RegistryCustomer extends javax.swing.JFrame {

    Customer custom;
    Signin in;
    RegistryCustomer regitryCustomer;

    
    public RegistryCustomer(Customer cst) {
        this.custom = cst;
        initComponents();
    }
    
    
    public RegistryCustomer(Signin sign) {
        this.in =sign;
        
    }
        
    public void checkText() {

        if (tfNombre1.getText().isEmpty()) {
            lAnuncioUsuario3.setText(" Type a user");
        } else {
            lAnuncioUsuario3.setText("");
        }
        if (tfpass1.getText().isEmpty()) {
            lAnuncioUsuario4.setText(" Type a password");
        } else {
            lAnuncioUsuario4.setText("");
        }
        if (tfpass1.getText().isEmpty()) {
            lAnuncioContraseña3.setText(" Type IP");
        } else {
            lAnuncioContraseña3.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre1 = new javax.swing.JTextField();
        tfpass1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lAnuncioContraseña3 = new javax.swing.JLabel();
        lAnuncioUsuario3 = new javax.swing.JLabel();
        lAnuncioUsuario4 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        tfRegresar = new javax.swing.JButton();
        tfUs1 = new javax.swing.JTextField();
        lAnuncio1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña");

        tfNombre1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombre1MouseClicked(evt);
            }
        });

        tfpass1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpass1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/o.png"))); // NOI18N

        lAnuncioContraseña3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lAnuncioContraseña3.setForeground(new java.awt.Color(255, 51, 51));
        lAnuncioContraseña3.setText(".");

        lAnuncioUsuario3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lAnuncioUsuario3.setForeground(new java.awt.Color(255, 51, 51));
        lAnuncioUsuario3.setText(".");

        lAnuncioUsuario4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lAnuncioUsuario4.setForeground(new java.awt.Color(255, 51, 51));
        lAnuncioUsuario4.setText(".");

        Registrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Registrar.setText("Registrarme");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        tfRegresar.setText("Regresar");
        tfRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRegresarActionPerformed(evt);
            }
        });

        tfUs1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfUs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUs1MouseClicked(evt);
            }
        });
        tfUs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUs1ActionPerformed(evt);
            }
        });

        lAnuncio1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lAnuncio1.setText("Ingrese los datos del usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfUs1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lAnuncioUsuario4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lAnuncioContraseña3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lAnuncioUsuario3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addComponent(lAnuncio1)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfRegresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Registrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tfRegresar)
                .addGap(14, 14, 14)
                .addComponent(lAnuncio1)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnuncioUsuario3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnuncioUsuario4))
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lAnuncioContraseña3))
                .addGap(36, 36, 36)
                .addComponent(Registrar)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombre1MouseClicked
        tfpass1.setEditable(true);
        tfpass1.setEditable(true);

    }//GEN-LAST:event_tfNombre1MouseClicked

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed

        checkText();
        boolean exist = custom.searchCustomer(tfUs1.getText());

        if (exist) {

            lAnuncioUsuario4.setText("");
            tfpass1.setEditable(false);

        } else {

            if ((tfNombre1.getText().isEmpty()) || (tfUs1.getText().isEmpty()) || (tfpass1.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Type Date");

            } else {
                String nombre = tfNombre1.getText();
                String us = tfUs1.getText();
                String pass = tfpass1.getText();
     
                custom.registryCustomer(nombre, us, pass);
                JOptionPane.showMessageDialog(this, "Correctly registered user");
                
                tfNombre1.setText("");
                tfUs1.setText("");
                tfpass1.setText("");

            }

        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void tfpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpass1ActionPerformed

    private void tfUs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUs1MouseClicked
        tfpass1.setEditable(true);
    }//GEN-LAST:event_tfUs1MouseClicked

    private void tfRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRegresarActionPerformed
        custom.back();
    }//GEN-LAST:event_tfRegresarActionPerformed

    private void tfUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUs1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAnuncio1;
    private javax.swing.JLabel lAnuncioContraseña3;
    private javax.swing.JLabel lAnuncioUsuario3;
    private javax.swing.JLabel lAnuncioUsuario4;
    private javax.swing.JTextField tfNombre1;
    private javax.swing.JButton tfRegresar;
    private javax.swing.JTextField tfUs1;
    private javax.swing.JTextField tfpass1;
    // End of variables declaration//GEN-END:variables
}
